export const API_URL = 'http://127.0.0.1:9000'
export const API_CITY = '/api/city/'
export const API_BOOKMARK = '/api/bookmark/'
export const API_CITY_COMMENT = 'comment/'
export const API_ENDPOINT_CITIES_FETCH = 'fetch/cities/'
export const API_ENDPOINT_CITY_FETCH = 'fetch/city/'
export const MASTER_KEY = 'SZppwi3ESEVpz19XVg0RjsrsK9KVIE2I'
